# Sandbox
a place to play with python

In [1]:
import numpy as np

In [12]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [37]:
rng = np.random.default_rng(0)
b = rng.random((4,2,3))
b

array([[[0.63696169, 0.26978671, 0.04097352],
        [0.01652764, 0.81327024, 0.91275558]],

       [[0.60663578, 0.72949656, 0.54362499],
        [0.93507242, 0.81585355, 0.0027385 ]],

       [[0.85740428, 0.03358558, 0.72965545],
        [0.17565562, 0.86317892, 0.54146122]],

       [[0.29971189, 0.42268722, 0.02831967],
        [0.12428328, 0.67062441, 0.64718951]]])

In [38]:
b[1][0][2]

0.5436249914654229

In [39]:
b<0.1

array([[[False, False,  True],
        [ True, False, False]],

       [[False, False, False],
        [False, False,  True]],

       [[False,  True, False],
        [False, False, False]],

       [[False, False,  True],
        [False, False, False]]])